services:
  mysql-r3mob:
    image: mysql:8.0
    container_name: mysql-r3mob
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
  adminer-r3mob:
    image: adminer
    container_name: adminer-r3mob
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql-r3mob

